name: mm_env
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pytest
  - tensorboard
  - pip:
      - accelerate==1.12.0
      - arviz==0.23.0
      - datasets==4.4.2
      - einops==0.8.1
      - flax==0.10.6
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - optax==0.2.6
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pymc==5.27.0
      - pyknos==0.16.0
      - pytensor==2.36.3
      - sbi==0.25.0
      - tensorstore==0.1.77
      - transformers==4.57.3
      - treescope==0.1.10
      - xarray==2025.12.0
      - xarray-einstats==0.9.1
      - zuko==1.5.0